---
apiVersion: v1
kind: Secret
metadata:
  name: test-worker-bmc-secret
  namespace: openshift-machine-api
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: test-worker
  namespace: openshift-machine-api
spec:
  online: true
  bootMACAddress: 52:54:00:7b:0e:c8
  bmc:
    address: redfish-virtualmedia+https://192.168.111.1:8000/redfish/v1/Systems/dc3479b0-89e2-4eb0-90be-9a662f512673
    credentialsName: test-worker-bmc-secret
    disableCertificateVerification: true
  automatedCleaningMode: disabled
  customDeploy:
    method: install_coreos
  rootDeviceHints:
    deviceName: "/dev/vda"
